version: '3'
services:

    nginx:
        image: nginx:alpine
        container_name: linktree_site
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=contact.moviedo.rigidcode.com,www.contact.moviedo.rigidcode.com
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=rigidcode.com
            - LETSENCRYPT_EMAIL=admin@rigicode.com
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./public_html:/app
        networks:
        - proxy
        restart: unless-stopped

networks:
    proxy:
        external:
            name: nginx-proxy
